<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('Usted sera redirigido al sitio seguro de webpay para pago en peso chileno.') ?>
            
</table>
	<table width="100%">
		<colgroup>
			<col width="50%">
			<col width="50%">
		</colgroup>
		<tr align="center">
			<td>
				<img src="<?php echo $this->getSkinUrl('images/webpay/webpay.png') ?>" border="0" />
			</td>
			
			</table>
            
            
        </li>
    </ul>
</fieldset>