<?php
$theme = $this->helper('mtbakery');
$equalHeight = $theme->getCfg('category_grid/equal_height');
$displayAddtocart = $theme->getCfg('category_grid/display_addtocart');
$displayAddtolink = $theme->getCfg('category_grid/display_addtolinks');
$compareHeader = $theme->getCfg('header/compare');
?>
<script type="text/javascript">
    <?php if ($equalHeight): ?>
    function setGridItemsEqualHeight($)
    {
        var winWidth = $(window).width();
        var SPACING = 20;
        if (winWidth >= 480)
        {
            $('.show-grid').removeClass("auto-height");
            var gridItemMaxHeight = 0;
            $('.show-grid > .item').each(function() {
                $(this).css("height", "auto");
                <?php if ($displayAddtocart == 2 || $displayAddtolink == 2): ?>
                var actionsHeight = $(this).find('.actions').height();
                $(this).css("padding-bottom", (actionsHeight + SPACING) + "px"); //Set new padding
                <?php endif; ?>
                gridItemMaxHeight = Math.max(gridItemMaxHeight, $(this).height());
            });
            $('.show-grid > .item').css("height", gridItemMaxHeight + "px");
        }
        else
        {
            $('.show-grid').addClass("auto-height");
            $('.show-grid > .item').css("height", "auto");
            $('.show-grid > .item').css("padding-bottom", "20px");
        }
    }
    <?php endif; ?>
    function setGridItem($){
        var winWidth = $(window).width();
        var col = <?php echo $theme->getCfg('category_grid/column_count');?>;
        if(winWidth > 768){
            newcol = col;
        }
        if(winWidth < 768 && winWidth >=640){
            newcol = <?php echo $theme->getCfg('category_grid/column_count_768');?>;
        }
        if(winWidth >=480 && winWidth <640){
            newcol = <?php echo $theme->getCfg('category_grid/column_count_640');?>;
        }
        if(winWidth < 480){
            newcol = <?php echo $theme->getCfg('category_grid/column_count_480');?>;
        }
        $i = 0;
        $('.show-grid > .item').each(function() {
            $i++;
            $(this).removeClass('first');
            $(this).removeClass('last');
            if(($i-1)%newcol==0){
                $(this).addClass('first');
            }else if($i%newcol==0){
                $(this).addClass('last');
            }
        });
    }
    $mt(function($) {
        var winWidth = $(window).width();
        var winHeight = $(window).height();
        var windowResize_t;
        $(window).resize(function() {
            var winNewWidth = $(window).width();
            var winNewHeight = $(window).height();
            if (winWidth != winNewWidth || winHeight != winNewHeight)
            {
                clearTimeout(windowResize_t);
                windowResize_t = setTimeout(function() {
                    $(document).trigger("themeResize");
                    <?php if ($equalHeight): ?>
                    setGridItemsEqualHeight($);
                    <?php endif; ?>
                    setGridItem($);
                }, 200);
            }
            winWidth = winNewWidth;
            winHeight = winNewHeight;
        });
        <?php if($compareHeader):?>
        $('.mt-maincompare').hover(
            function () {
                $(this).addClass('compare-active').find('.mtajaxcompare').stop().delay(200).slideDown();
            },
            function () {
                $(this).removeClass('compare-active').find('.mtajaxcompare').stop().delay(200).slideUp();
            }
        );
        <?php endif; ?>
        $('.setting-big').hover(
            function () {
                $(this).addClass('setting-bi-active').find('.mtsettingbig').stop().delay(200).slideDown();
            },
            function () {
                $(this).removeClass('setting-bi-active').find('.mtsettingbig').stop().delay(200).slideUp();
            }
        );
        $("#select-language").selectbox();
        $("#select-currency").selectbox();
		//lazyload
        $("img.lazy").lazy({
            effect : "fadeIn",
            effectTime: 800,
            threshold: 50, 
            afterLoad: function(element) {
                <?php if ($equalHeight): ?>
				setGridItemsEqualHeight($);
				<?php endif; ?>
            }
        });
        var text = $(".form-language a.sbSelector").text().toLowerCase();
        $(".form-language a.sbSelector").css({
            "background-image":"url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>media/wysiwyg/magenthemes/languages/"+text+".png')",
            "background-repeat":"no-repeat",
            "background-position":"left center"
        });

		//Back to top
		$(window).scroll(function () {
			if ($(this).scrollTop() > 100) {
				$('#back-top').fadeIn();
			} else {
				$('#back-top').fadeOut();
			}
		});
		$('#back-top a').click(function () {
			$('body,html').animate({
				scrollTop: 0
			}, 800);
			return false;
		});


        $('.bottom-content').click(function () {
            $('html, body').animate({
                    scrollTop: $('.show-grid-slide').height()
                },
                800);
            return false;
        });

        //Cart header
        $('.mt-maincart').hover(
            function () {
                $(this).addClass('cart-active').find('.ajaxcart').stop().delay(200).slideDown();
            },
            function () {
                $(this).removeClass('cart-active').find('.ajaxcart').stop().delay(200).slideUp();
            }
        );
        //Quickview
        $('.product-quickview').live('click', function() {
            $.colorbox({
                iframe: true,
                href:this.href,
                opacity:	0.5,
                speed:		300,
                current:	'{current} / {total}',
                close:      "close",
                innerWidth:'765px',
                innerHeight:'650px',
                onOpen: function(){
                    $('#cboxLoadingGraphic').addClass('box-loading');
                },
                onComplete: function(){
                    setTimeout(function(){
                        $('#cboxLoadingGraphic').removeClass('box-loading');
                    },1300);
                }
            });
        });

        $('.show-quickview').live('click', function(e){
            if($('.btn-cart-mobile').length == 0){
                $('[data-id=quickview-' + $(this).attr('data-id')+']').trigger('click');
            }else{
                return window.location.href=$(this).attr('data-submit');
            }
        });
    });
    $mt(window).load(function(){
        <?php if ($equalHeight): ?>
            setGridItemsEqualHeight($mt);
        <?php endif; ?>
        setGridItem($mt);
        $mt.browserSelector();
        if($mt("html").hasClass("chrome")) {
            $mt.smoothScroll();
        }
        if($mt("html").hasClass("safari")) {
            $mt.smoothScroll();
        }
        $mt(".mt-tooltip").tooltip();


        var selectToggle = '<i class="fa fa-angle-down"></i>',
			flextPrev = '<i class="fa fa-angle-left"></i>',
            flextNext = '<i class="fa fa-angle-right"></i>';
			
			$mt(".flex-direction-nav a, .more-views .more-views-prev, .more-views .more-views-next").empty();
			$mt(".more-views").addClass("nav-wrapper-view");
			//$mt(".sbToggle").append(selectToggle);
			$mt(".flex-direction-nav a.flex-prev").append(flextPrev);
			$mt(".flex-direction-nav a.flex-next").append(flextNext);

        wow = new WOW(
            {
                boxClass:     'wow',
                animateClass: 'animated',
                offset:       100
            }
        );
        wow.init();
    });
	$mt(".accordion-footer").addClass("accordion-show");
	$mt(".accordion-footer").click(function(){
		if($mt(this).parent().next().is(":visible")){
			$mt(this).addClass("accordion-show");
		}else{
			$mt(this).removeClass("accordion-show");
		}
		$mt(this).parent().next().toggle(400);
	});
	//Background category header//
	$mt(document).ready(function(){
        var iconSearch = $mt(".quick-access").find(".mt-icon-ajax").find(".fa-search"),
            formSearch = $mt(".quick-access").find(".form-search"),
            headerOverlay = $mt(".header-content").find(".header-act");
        $mt(iconSearch).click(function(){
            if($mt(formSearch).is(":visible")){
                $mt(formSearch).fadeOut(100);
                $mt(this).removeClass("fa-arrows-alt").addClass("fa-search");
                $mt(headerOverlay).removeClass("header-overlay");
                $mt(this).attr("data-icon","U");
            } else {
                $mt(formSearch).fadeIn(100);
                $mt(this).removeClass("fa-search").addClass("fa-arrows-alt");
                $mt(headerOverlay).addClass("header-overlay");
                $mt(this).attr("data-icon","M");
            }
        });
	});



    function iconFontAwesome() {
        //add font icon awesome

        $mt(".top-link .links li a").append("<i></i>");
        $mt(".top-link .links li.first i").addClass("fa fa-user");
        $mt(".top-link .links li a.top-link-cart i").addClass("fa fa-shopping-cart");
        $mt(".top-link .links li a.top-link-wishlist i").addClass("fa fa-heart-o");
        $mt(".top-link .links li a.top-link-checkout i").addClass("fa fa-check");
        $mt(".top-link .links li.last i").addClass("fa fa-unlock-alt");
    }
</script>