<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Themes
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<?php
$enable = Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart');
?>
<?php $_cartQty = $this->getSummaryCount() ?>
<?php if ($enable) {?>
    <span class="mt-cart-loading">Loading...</span>
    <div class="mt-cart">
        <div class="border-left"></div>
        <div class="mt-icon-ajaxcart">
            <a class="mt-cart-label" href="<?php echo $this->getUrl('checkout/cart') ?>">
            <span class="icon-cart">

                <span data-icon="" aria-hidden="true" class="fs1"></span>
            </span>
            <span class="heading-cart">
                <span class="mt-cart-title"><?php echo $this->__('My Bag') ?></span>
                <span class="print">
                    <?php //echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                    <?php print (!empty($_cartQty)) ? $_cartQty : '0' ;?>
                    <!--<span><?php //echo $this->__('item(s)') ?></span>-->
                </span>
            </span>
            </a>
        </div>
        <div class="border-right"></div>
        <div class="ajaxcart">
            <div class="search-form-border"></div>
            <div class="mt-ajax-container">
                <?php
                $_items = $this->getRecentItems($_cartQty);
                if(count($_items)):
                    ?>
                    <ul class="clearfix">
                        <?php foreach($_items as $_item): ?>
                            <?php echo $this->getItemHtml($_item) ?>
                        <?php endforeach; ?>
                    </ul>
                    <p class="subtotal">
                        <?php if ($this->canApplyMsrp()): ?>
                            <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                        <?php else: ?>
                            <span class="label"><?php echo $this->__('Total:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                            <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                                <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                            <?php endif; ?>
                        <?php endif; ?>
                    </p>
                    <div class="mt-ajax-checkout">
                        <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="view-cart">
                            <span><?php echo $this->__('View cart') ?></span>
                        </a>
                        <?php if(Mage::getStoreConfig('opc/global/status')){?>
                            <a href="<?php echo $this->getUrl('onepage') ?>"><span><?php echo $this->__('Checkout') ?></span></a>
                        <?php }else{?>
                            <a href="<?php echo $this->getCheckoutUrl() ?>"><span><?php echo $this->__('Checkout') ?></span></a>
                        <?php }?>
                    </div>
                <?php else: ?>
                    <p class="no-items-in-cart"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
                <?php endif ?>
            </div>
        </div>
    </div>
<?php } else {?>
<span class="mt-cart-loading">Loading...</span>
<div class="mt-cart">
    <div class="border-left"></div>
    <div class="mt-icon-ajaxcart">
        <a class="mt-cart-label" href="<?php echo $this->getUrl('checkout/cart') ?>">
            <span class="icon-cart">

                <span data-icon="" aria-hidden="true" class="fs1"></span>
            </span>
            <span class="heading-cart">
                <span class="mt-cart-title"><?php echo $this->__('My Bag') ?></span>
                <span class="print">
                    <?php //echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                    <?php print (!empty($_cartQty)) ? $_cartQty : '0' ;?>
                    <!--<span><?php //echo $this->__('item(s)') ?></span>-->
                </span>
            </span>
        </a>
    </div>
    </div>
<?php }?>
<script type="text/javascript">
    var datatext = {};
    datatext.load = '<?php echo $this->__('processing');?>';
</script>