<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
$_helper = $this->helper('catalog/output');
$theme = $this->helper('mtbakery');
/* @var $this MT_Widget_Block_Widget_Collection */
$productCollection  = $this->getData('collection');
$count              = $productCollection ? $productCollection->count() : 0;
$carousel           = $this->getData('carousel');
$row                = $this->getData('row');
$column             = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
/* @var $helper Mage_Catalog_Helper_Image */
$helper             = Mage::helper('catalog/image');
?>
<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <?php $i=0; foreach ($productCollection as $_product): ?>
        <?php /* @var $product Mage_Catalog_Model_Product */ ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel">
        <?php endif ?>
        <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        <div class="category-products category-custom category-products-list">
            <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
                <?php endif ?>
                <?php $i++ ?>
                <li class="item clearfix">
                    <div class="catpanel-collection">
                        <div class="product-hover col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                 <img class="img-responsive lazyOwl" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(271 ,465); ?>" width="271" height="465" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </a>
                            <div class="product-intification-box"><i class="fa fa-circle-o-notch fa-spin"></i></div>
                        </div>
                        <div class="top-inner-collection col-lg-8 col-md-8 col-sm-8 col-xs-8">
                            <h3 class="product-name">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                    <?php echo $this->escapeHtml($_product->getName()) ?>
                                </a>
                            </h3>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>

                        </div>
                    </div>
                </li>
                <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
             </ul>
        </div>
        <?php endif ?>
        <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>
