<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
/* @var $this MT_Widget_Block_Widget */
$_id                = $this->getConfig('id');
$_title             = $this->getConfig('widget_title');
$t                  = microtime();
?>
<?php if ($this->checkCollectionSize('collection', $this->getData('mode'))): ?>
<div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $_id ?>">
    <?php if ($_title): ?>
        <h2><?php echo $_title ?></h2>
    <?php endif ?>
    <?php echo $this->renderCollection('collection', $this->getData('mode'), 'mt/widget/collection.phtml') ?>
</div>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>mt/widget/frontend.js"></script>
<script type="text/javascript">
    new MT.Widget('<?php echo $_id ?>', {
        parallax: <?php echo $this->getConfig('parallax') ?>,
        carousel: <?php echo $this->getConfig('carousel') ?>
    });
</script>
<?php //Mage::log(microtime() - $t) ?>
<?php endif ?>
