<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
/* @var $this MT_Widget_Block_Widget */
$_id                = $this->getConfig('id');
$_title             = $this->getConfig('widget_title');
$t                  = microtime();
?>
<div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $_id ?>">
    <div class="block clearfix">
        <div class="block-title">
            <strong>
                <?php if ($_title):?>
                    <span><?php echo $_title?></span>
                <?php endif ?>
            </strong>
        </div>
    </div>
    <?php echo $this->renderCollection('collection', $this->getData('mode'), 'mt/widget/collection-custom.phtml') ?>
</div>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>mt/widget/frontend.js"></script>
<script type="text/javascript">
    new MT.Widget('<?php echo $_id ?>', {
        animation: <?php echo $this->getConfig('animation') ?>,
        parallax: <?php echo $this->getConfig('parallax') ?>,
        carousel: <?php echo $this->getConfig('carousel') ?>,
        kenburns: <?php echo $this->getConfig('kenburns') ?>
    });
</script>
<?php //Mage::log(microtime() - $t) ?>
